app/app.py
from flask import Flask, render_template, request
from datetime import datetime
from app import utils

def error_handler_404(error):
    locale, strings = utils.localization(request.path.split("/")[1])
    return render_template("errors.html", code="404", strings=strings), 404

def error_handler_500(error):
    locale, strings = utils.localization(request.path.split("/")[1])
    return render_template("errors.html", code="500", strings=strings), 500


# def create_app(test_config=None):
app = Flask(__name__, instance_relative_config=True)


# Apply the blueprints to the app
from app.blueprints import home, roadmap, changelog, beta, newsletter

app.register_blueprint(home.bp,     url_prefix="/")
app.register_blueprint(roadmap.bp,  url_prefix="/roadmap")
app.register_blueprint(changelog.bp,url_prefix="/changelog")
app.register_blueprint(beta.bp,     url_prefix="/beta")
app.register_blueprint(newsletter.bp, url_prefix="/newsletter")

app.register_blueprint(home.bp,     url_prefix="/<locale>/")
app.register_blueprint(roadmap.bp,  url_prefix="/<locale>/roadmap")
app.register_blueprint(changelog.bp,url_prefix="/<locale>/changelog")
app.register_blueprint(beta.bp,     url_prefix="/<locale>/beta")
app.register_blueprint(newsletter.bp,     url_prefix="/<locale>/newsletter")

# app.register_blueprint(redirects.bp)
app.add_url_rule("/", endpoint="home.index")
app.register_error_handler(404, error_handler_404)


@app.template_filter()
def time_format(date_string: str):
    date = datetime.strptime(date_string, "%Y-%m-%d")
    return date.strftime("%B %d, %Y")

# @app.route("/robots.txt")
# def robots():
#     return "ROBOTS"


# g.localization = "DE"
# Error Handlers
# app.register_error_handler(404, page_not_found)
# app.register_error_handler(500, page_not_found)

app/blueprints/beta.py
from flask import Blueprint

from flask import render_template, request, current_app, redirect, url_for, flash
from flask import abort

from app import utils
from app.mailchimp import Mailchimp
from app.connect import ConnectAPI

bp = Blueprint("beta", __name__, url_prefix="/")


@bp.route("/")
def index(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    return render_template("beta/index.html", locale=locale, strings=strings)


@bp.route("/join", methods=('GET', 'POST'))
def join(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))

    if request.method == 'POST':
        fname = request.form.get('fname')
        lname = request.form.get('lname')
        email = request.form.get('email')
        newsletter = request.form.get('newsletter')
        success_newsletter = True
        if newsletter:
            success_newsletter = Mailchimp().addSubscriber(email, fname, lname)
        
        success_testflight = ConnectAPI().invite_tester(email, fname, lname)

        if not (success_testflight or success_newsletter):
            # flash(strings['error'])
            print("ERROR")
            # TODO

        return redirect(url_for('beta.thanks', name=fname if fname != None else "", locale=locale))

    return render_template("beta/join.html", strings=strings)


@bp.route("/thanks/<name>")
def thanks(name: str, **options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    return render_template("beta/thanks.html", locale=locale, strings=strings, name=name)

app/blueprints/beta/__init__.py
from flask import Blueprint

from flask import render_template, request, current_app, redirect, url_for, flash
from flask import abort

from app import utils
from app.mailchimp import Mailchimp
from app.blueprints.beta.forms import *

bp = Blueprint("beta", __name__, url_prefix="/")


@bp.route("/")
def index(**options):
    locale, strings = utils.localization(options.get('locale', 'en'), 'beta.index')
    return render_template("beta/index.html", locale=locale, strings=strings)


@bp.route("/join", methods=('GET', 'POST'))
def join(**options):
    locale, strings = utils.localization(options.get('locale', 'en'), 'beta.join')

    if request.method == 'POST':
        fname = request.form.get('fname')
        lname = request.form.get('lname')
        mail = request.form.get('email')
        success = Mailchimp().addSubscriber(fname, lname, mail)
        if not success:
            # flash(strings['error'])
            print("ERROR")
        return redirect(url_for('beta.thanks', name=fname, locale=locale))

    return render_template("beta/join.html", strings=strings)


@bp.route("/thanks/<name>")
def thanks(name: str, **options):
    locale, strings = utils.localization(options.get('locale', 'en'), 'beta.thanks')
    return render_template("beta/thanks.html", locale=locale, strings=strings, name=name)

app/blueprints/changelog.py
from flask import Blueprint

from flask import render_template, request, current_app, redirect, url_for, flash
from flask import abort

from app import utils

bp = Blueprint("changelog", __name__, url_prefix="/")


@bp.route("/")
def index(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    versions = utils.get_data('changelog.json')
    return render_template("changelog.html", locale=locale, strings=strings, versions=versions)

app/blueprints/home.py
from flask import Blueprint

from flask import render_template, request, current_app, redirect, url_for, flash
from flask import abort

from app import utils

bp = Blueprint("home", __name__, url_prefix="/")


@bp.route("/")
def index(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    return render_template("home.html", locale=locale, strings=strings)

@bp.route("/imprint")
def imprint(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    return render_template("imprint.html", locale=locale, strings=strings)

@bp.route("/privacy")
def privacy(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    return render_template("privacy.html", locale=locale, strings=strings)

@bp.route("/about")
def about(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    return render_template("about.html", locale=locale, strings=strings)

app/blueprints/newsletter.py
from flask import Blueprint

from flask import render_template, request, current_app, redirect, url_for, flash
from flask import abort

from app import utils
from app.mailchimp import Mailchimp
from app.connect import ConnectAPI

bp = Blueprint("newsletter", __name__, url_prefix="/")


@bp.route("/")
def index(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))

    if request.method == 'POST':
        fname = request.form.get('fname')
        lname = request.form.get('lname')
        email = request.form.get('email')

        success_newsletter = Mailchimp().addSubscriber(email, fname, lname)

        if not (success_newsletter):
            # flash(strings['error'])
            print("ERROR")
            # TODO

    return render_template("newsletter/index.html", locale=locale, strings=strings)


@bp.route("/thanks/<name>")
def thanks(name: str, **options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    return render_template("newsletter/thanks.html", locale=locale, strings=strings, name=name)

app/blueprints/roadmap.py
from flask import Blueprint

from flask import render_template, request, current_app, redirect, url_for, flash
from flask import abort

from app import utils

bp = Blueprint("roadmap", __name__, url_prefix="/")


@bp.route("/")
def index(**options):
    locale, strings = utils.localization(options.get('locale', 'en'))
    html = utils.get_data("roadmap.html")
    return render_template("roadmap.html", locale=locale, strings=strings)

app/templates/about.html
{% extends "base/base.html" %}
{% set title = "About" %}

{% block css %}
{% endblock %}

{% block fullwidth %}
ABOUT
{% endblock %}

app/templates/base/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{{title}} · Bootstrap</title>

    <!-- FAVICONS -->
    <link rel="apple-touch-icon" sizes="57x57" href="{{url_for('static', filename='favicons/apple-icon-57x57.png')}}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{url_for('static', filename='favicons/apple-icon-60x60.png')}}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{url_for('static', filename='favicons/apple-icon-72x72.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static', filename='favicons/apple-icon-76x76.png')}}">
    <link rel="apple-touch-icon" sizes="114x114"
        href="{{url_for('static', filename='favicons/apple-icon-114x114.png')}}">
    <link rel="apple-touch-icon" sizes="120x120"
        href="{{url_for('static', filename='favicons/apple-icon-120x120.png')}}">
    <link rel="apple-touch-icon" sizes="144x144"
        href="{{url_for('static', filename='favicons/apple-icon-144x144.png')}}">
    <link rel="apple-touch-icon" sizes="152x152"
        href="{{url_for('static', filename='favicons/apple-icon-152x152.png')}}">
    <link rel="apple-touch-icon" sizes="180x180"
        href="{{url_for('static', filename='favicons/apple-icon-180x180.png')}}">
    <link rel="icon" type="image/png" sizes="192x192"
        href="{{url_for('static', filename='favicons/android-icon-192x192.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='favicons/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{url_for('static', filename='favicons/favicon-96x96.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='favicons/favicon-16x16.png')}}">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#000B25">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#000B25">


    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/0042a44157.js"></script>

    <!-- Styles for Page -->
    <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">

    <!-- Custom Stylesheets for subpages -->
    {% block css %}{% endblock %}

</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark" id="mainNav" style="opacity: 0.95;">
        <div class="container">
            <a class="navbar-brand d-xl-flex justify-content-xl-end align-items-xl-center js-scroll-trigger"
                href="{{ url_for('home.index', locale=locale) }}">
                <img src="{{ url_for('static', filename='logos/banner_dark.png')}}" height=24 class="masthead-brand" />
            </a>
            <button data-toggle="collapse" data-target="#navbarMain" class="navbar-toggler navbar-toggler-right"
                type="button" data-toogle="collapse" aria-controls="navbarMain" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>



            <div class="collapse navbar-collapse" id="navbarMain">
                <ul class="navbar-nav">
                    <li class="nav-item {% if request.blueprint == 'home' %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('home.index', locale=locale) }}">Home
                            {% if request.blueprint == "home" %}<span class="sr-only">(current)</span>{% endif %}</a>
                    </li>
                    <!-- <li class="nav-item {% if request.blueprint == 'roadmap' %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('roadmap.index', locale=locale) }}">Roadmap
                            {% if request.blueprint == "roadmap" %}<span class="sr-only">(current)</span>{% endif %}</a>
                    </li>
                    <li class="nav-item {% if request.blueprint == 'changelog' %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('changelog.index', locale=locale) }}">Changelog
                            {% if request.blueprint == "changelog" %}<span
                                class="sr-only">(current)</span>{% endif %}</a>
                    </li>
                    <li class="nav-item {% if request.blueprint == 'about' %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('home.index', locale=locale) }}">About
                            {% if request.blueprint == "about" %}<span class="sr-only">(current)</span>{% endif %}</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('beta.index', locale=locale) }}">Beta Test</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('newsletter.index', locale=locale) }}">Newsletter</a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>


    <main>
        <div class="container">
            {% block fullwidth %}{% endblock %}
            <div class="row">
                <div class="col-sm-10">
                    {% block content %}{% endblock %}
                </div>
                <div class="col" style="background-color: blue;">
                    {% block sidebar %}{% endblock %}
                </div>
            </div>
        </div>
    </main>


    <!-- Footer -->
    <footer>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('home.index', locale=locale) }}">
                <img src="{{ url_for('static', filename='logos/banner_light.png')}}" height=30 />
            </a>

            <ul style="width: 100%" class="navbar-nav nav-fill justify-content-center">
                <!-- Twitter -->
                <li class="nav-item">
                    <a class="nav-link" href="https://twitter.com/abjc_app">
                        <i class="fab fa-twitter"> </i> Twitter
                    </a>
                </li>

                <!-- GitHub -->
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/ABJC">
                        <i class="fab fa-github"> </i> GitHub
                    </a>
                </li>

                <!-- About -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home.about', locale=locale) }}">
                        <i class="fas fa-address-card"> </i> About
                    </a>
                </li>

                <!-- Privacy -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home.privacy', locale=locale) }}">
                        <i class="fas fa-user-secret"> </i> Privacy
                    </a>
                </li>

                <!-- Imprint -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home.imprint', locale=locale) }}">
                        <i class="fa fa-gavel"> </i> Imprint
                    </a>
                </li>
            </ul>
        </nav>
    </footer>

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/base.js')}}"></script> -->

    <!-- Custom Javascript for subpages -->
    {% block script %}{% endblock %}

</html>

app/templates/base/cover.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Noah Kamara">
  <title>{% block pagetitle %}{% endblock %} · ABJC</title>

  <!-- FAVICONS -->
  <link rel="apple-touch-icon" sizes="57x57" href="{{url_for('static', filename='favicons/apple-icon-57x57.png')}}">
  <link rel="apple-touch-icon" sizes="60x60" href="{{url_for('static', filename='favicons/apple-icon-60x60.png')}}">
  <link rel="apple-touch-icon" sizes="72x72" href="{{url_for('static', filename='favicons/apple-icon-72x72.png')}}">
  <link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static', filename='favicons/apple-icon-76x76.png')}}">
  <link rel="apple-touch-icon" sizes="114x114" href="{{url_for('static', filename='favicons/apple-icon-114x114.png')}}">
  <link rel="apple-touch-icon" sizes="120x120" href="{{url_for('static', filename='favicons/apple-icon-120x120.png')}}">
  <link rel="apple-touch-icon" sizes="144x144" href="{{url_for('static', filename='favicons/apple-icon-144x144.png')}}">
  <link rel="apple-touch-icon" sizes="152x152" href="{{url_for('static', filename='favicons/apple-icon-152x152.png')}}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='favicons/apple-icon-180x180.png')}}">
  <link rel="icon" type="image/png" sizes="192x192"
    href="{{url_for('static', filename='favicons/android-icon-192x192.png')}}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='favicons/favicon-32x32.png')}}">
  <link rel="icon" type="image/png" sizes="96x96" href="{{url_for('static', filename='favicons/favicon-96x96.png')}}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='favicons/favicon-16x16.png')}}">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">


  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

  <!-- Styles for Page -->
  <link href="{{ url_for('static', filename='css/testflight.css') }}" rel="stylesheet">


</head>

<body class="text-center">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <a href="{{ url_for('home.index', locale=locale) }}" class="masthead mb-auto">
      <img src="{{ url_for('static', filename='logos/banner_dark.png')}}" height=50 class="masthead-brand" />
    </a>


    <main role="main" class="cover">

      <h1 class="cover-heading">{% block title %}{% endblock %}</h1>
      <p class="lead">{% block subtitle %}{% endblock %} </p>

      {% block content %}{% endblock %}

      <p class="lead"></p>
      {% if not isCustomButton %}
      <a href="{% block button_href %}{% endblock %}"
        class="btn btn-lg btn-primary">{% block button %}{% endblock %}</a>
      {% else %}
      {% block button_custom %}{% endblock %}
      {% endif %}
      </p>




    </main>

    <footer class="mastfoot mt-auto">
      <div class="inner">
        <p>© 2020 Copyright: <a href="noahkamara.github.io">Noah Kamara</a></p>
      </div>
    </footer>
  </div>
</body>

</html>

app/templates/beta/index.html
{% extends "base/cover.html" %}

{% block pagetitle %} 
  {{ strings.beta.index.title }}
{% endblock %}

{% block title %} 
  {{ strings.beta.index.title }}
{% endblock %}

{% block subtitle %}
  {{ strings.beta.index.subtitle }}
{% endblock %}

{% block button %}
  {{ strings.beta.index.button }}
{% endblock %}

{% block button_href %}
  {{ url_for('beta.join', locale=locale) }}
{% endblock %}

app/templates/beta/join.html
{% extends "base/cover.html" %}
{% set isCustomButton = True %}

{% block pagetitle %} 
  {{ strings.beta.join.title }}
{% endblock %}

{% block title %} 
  {{ strings.beta.join.title }}
{% endblock %}

{% block subtitle %}
  {{ strings.beta.join.subtitle }}
{% endblock %}

{% block content %}
<form method="POST" class="lead" style="display:table; margin:auto;">
  <div class="form-row">
    <div class="form-group col-md-6">
      <input name="fname" type="text" class="form-control" placeholder="{{ strings.beta.join.form.fname }}">
    </div>
    <div class="form-group col-md-6">
      <input id="inputlname" name="lname" type="text" class="form-control" placeholder="{{ strings.beta.join.form.lname }}">
    </div>
  </div>
  <div class="form-group">
    <input required name="email" type="text" class="form-control" id="inputEmail" aria-describedby="emailHelp" placeholder="{{ strings.beta.join.form.email }}">
    <small id="inputEmail" class="form-text text-muted">{{ strings.beta.join.form.email_info }}</small>
  </div>
  <div class="form-group">
    <div id="formcheck" class="form-check">
      <input checked type="checkbox" class="form-check-input" name="newsletter" id="newsletter">
      <label class="form-check-label" for="newsletter">{{ strings.beta.join.form.newsletter }}</label>
    </div>
    <small id="formcheck" class="form-text text-muted">{{ strings.beta.join.form.newsletter_info }}</small>
  </div>
  
  <button type="submit" class="btn btn-lg btn-primary">{{ strings.beta.join.form.submit }}</button>
</form>
{% endblock %}

app/templates/changelog.html
{% extends "base/base.html" %}
{% set title = "Changelog" %}

{% block css %}
<link href="{{ url_for('static', filename='css/changelog.css') }}" rel="stylesheet">
{% endblock %}

{% block fullwidth %}
{% for v in versions %}
<div class="version" id="{{v.version}}">
    <h1>{{ v.version.replace("v","") }} {{ v.date | time_format }} {% if v.tagline != None %} - {{v.tagline}}{% endif %}</h1>
    
    <div class="row" style="width: 100%">
        <div class="col-md-6 nopadding">
            <h2>New Features</h2>
            {% for feature in v.changelog.features %}
                <div> 
                    <h3>{{ feature.title }}</h3>
                    <p>{{ feature.descr }}</p>
                    <img src="https://picsum.photos/320/180" width=100%/>
                    {% if feature.img %}{% endif %}
                </div>
            {% endfor %}
        </div>
        <div class="col">
            <h2>Bug Fixes & Improvements</h2>
            <ul>
                {% for change in v.changelog.changes %}
                    <li>{{ change }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

app/templates/errors.html
{% extends "base/base.html" %}
{% set title = "Home" %}


    


{% block css %}
{% endblock %}

{% block fullwidth %}
    <div class="container align-items-center" style="text-align: center;">
        <h1>{{ code }}</h1>
        <h5>{{ strings.errors[code].title }}</h5>
    </div>
    
{% endblock %}

app/templates/home.html
{% extends "base/base.html" %}
{% set title = "Home" %}

{% block css %}
{% endblock %}

{% block fullwidth %}
HOME
{% endblock %}

app/templates/imprint.html
{% extends "base/base.html" %}
{% set title = "Imprint" %}

{% block css %}
{% endblock %}

{% block fullwidth %}
IMPRINT
{% endblock %}

app/templates/newsletter/index.html
{% extends "base/cover.html" %}
{% set isCustomButton = True %}

{% block pagetitle %} 
  {{ strings.newsletter.index.title }}
{% endblock %}

{% block title %} 
  {{ strings.newsletter.index.title }}
{% endblock %}

{% block subtitle %}
  {{ strings.newsletter.index.subtitle }}
{% endblock %}

{% block content %}
<form method="POST" class="lead" style="display:table; margin:auto;">
  <div class="form-row">
    <div class="form-group col-md-6">
      <input name="fname" type="text" class="form-control" placeholder="{{ strings.newsletter.index.form.fname }}">
    </div>
    <div class="form-group col-md-6">
      <input id="inputlname" name="lname" type="text" class="form-control" placeholder="{{ strings.newsletter.index.form.lname }}">
    </div>
  </div>
  <div class="form-group">
    <input required name="email" type="text" class="form-control" id="inputEmail" aria-describedby="emailHelp" placeholder="{{ strings.newsletter.index.form.email }}">
  </div>
  
  <button type="submit" class="btn btn-lg btn-primary">{{ strings.newsletter.index.form.submit }}</button>
</form>
{% endblock %}

app/templates/newsletter/thanks.html
{% extends "base/cover.html" %}
{% set isCustomButton = True %}

{% block pagetitle %} 
  {{ strings.beta.thanks.title }}
{% endblock %}

{% block title %} 
  {{ strings.beta.thanks.title|replace("<name>", name)}}
{% endblock %}

{% block subtitle %}
  {{ strings.beta.thanks.subtitle}}
{% endblock %}

app/templates/privacy.html
{% extends "base/base.html" %}
{% set title = "Privacy" %}

{% block css %}
{% endblock %}

{% block fullwidth %}
PRIVACY
{% endblock %}

app/templates/roadmap.html
{% extends "base/base.html" %}
{% set title = "Roadmap" %}

{% block css %}
{% endblock %}

{% block fullwidth %}
ROADMAP
{% endblock %}